Feature/001 homepage
Listek93/coderscamp-projekt-restaurant pull request #11
Opened 2022-01-26 21:45 UTC by JochenL05

I merged the new "dev" branch to this branch. I corrected the things that were mentioned after the code review. Please check and let me know if everything is fine now

2022-01-28 01:53 UTC, AleksandraZochowska requested changes
All is good, just add those 4 recommended minor CSS changes & it'll be ready to merge

2022-01-28 01:53 UTC, AleksandraZochowska commented on src/components/Description/Description.css
> +  padding: 100px;
for responsiveness reasons, I'd recommend changing to: ` padding: 100px 20px;`

2022-01-28 01:53 UTC, AleksandraZochowska commented on src/components/Description/Description.css
> +  height: 60px;
for responsiveness reasons I'd recommend removing the `height: 60px;` rule

2022-01-28 01:53 UTC, AleksandraZochowska commented on src/components/Mainview/Mainview.css
> +  background-size: 100%;
For responsiveness reasons, I'd recommend changing to:
`background-size: cover;
background-position: center;`

2022-01-28 01:53 UTC, AleksandraZochowska commented on src/components/Mainview/Mainview.css
> +  height: calc(var(--component-lenght)*2);
For responsiveness reasons, I'd recommend changing to:
`height: 100vh;`

2022-01-29 20:39 UTC, JochenL05 commented
I changed the highlighted parts of the code and pushed it.

2022-02-04 15:06 UTC, merged